AppDevProjectGroup27/Areas/Admin/Controllers/SpecialController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using AppDevProjectGroup27.Data;
using AppDevProjectGroup27.Utility;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using System.Net.Mail;
using System.Net;
using AppDevProjectGroup27.Models.ViewModels;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using AppDevProjectGroup27.Models;

namespace AppDevProjectGroup27.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.ManagerUser)]
    [Area("Admin")]
    public class SpecialController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IWebHostEnvironment _hostEnvironment;

        public SpecialController(ApplicationDbContext db, UserManager<IdentityUser> userManager, IWebHostEnvironment hostEnvironment)
        {
            _db = db;
            _userManager = userManager;
            _hostEnvironment = hostEnvironment;
        }

        [TempData]
        public string StatusMessage { get; set; }

        //Get
        public async Task<IActionResult> Index()
        {
            SpecialVM objSpecial = new SpecialVM();
            objSpecial.MenuItems = await _db.MenuItems.Include(m => m.Category).Include(m => m.SubCategory).Where(m => m.OnSpecial == true && m.AvaQuantity > 0).ToListAsync();
            return View(objSpecial);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(SpecialVM objSpecial)
        {
            objSpecial.MenuItems = await _db.MenuItems.Include(m => m.Category).Include(m => m.SubCategory).Where(m => m.OnSpecial == true && m.AvaQuantity > 0).ToListAsync();


            if (string.IsNullOrWhiteSpace(objSpecial.Subject))
                return RedirectToAction(nameof(Index));

            else
            {

                var AllCustomersEmails = _userManager.GetUsersInRoleAsync(SD.CustomerEndUser).Result.ToList();
                if (AllCustomersEmails.Count() > 0)
                {
                    List<string> AllCustomersNames = new List<string>(0);
                    try
                    {
                        foreach (var item in AllCustomersEmails)
                        {
                            var tempName = await _db.ApplicationUser.Where(a => a.Email == item.Email).Select(a => a.Name).SingleAsync();
                            AllCustomersNames.Add(tempName);
                        }
                        if (AllCustomersNames.Count > 0)
                        {
                            for (int x = 0; x < AllCustomersNames.Count(); x++)
                            {
                                if (SendEmail(AllCustomersNames[x], AllCustomersEmails[x].Email, objSpecial.Subject, objSpecial.MenuItems) == true)
                                {
                                    StatusMessage = "Emails Sent to Customers Successfully.";
                                }
                                else
                                {
                                    objSpecial.StatusMessage = "Error : Unable to Send Emails to Customers.";
                                    objSpecial.MenuItems = await _db.MenuItems.Include(m => m.Category).Include(m => m.SubCategory).Where(m => m.OnSpecial == true && m.AvaQuantity > 0).ToListAsync();
                                    return View(objSpecial);
                                }
                                // In the above send email, the last parameter is left blank until 
                                // Code for the Body is done successfully
                                // Also note the SendEmail will not an email currently, because smtp.SendMessage() is commented below.
                            }
                        }
                        else
                        {
                            StatusMessage = "Error : There are no Customer Names.";
                        }
                    }
                    catch
                    {
                        StatusMessage = "Error : Unable to retrieve Customers' Names.";
                    }
                }
                else
                {
                    StatusMessage = "Error : No Customers exist to send the Newsletter to.";
                }

                objSpecial.StatusMessage = StatusMessage;
                objSpecial.MenuItems = await _db.MenuItems.Include(m => m.Category).Include(m => m.SubCategory).Where(m => m.OnSpecial == true && m.AvaQuantity > 0).ToListAsync();
                return View(objSpecial);
            }
        }
        public bool SendEmail(string Name, string Email, string Sub, IEnumerable<MenuItems> objMenuItems)
        {
            try
            {
                // locating the Templete's path
                var PathToFile = _hostEnvironment.WebRootPath + Path.DirectorySeparatorChar.ToString()
                   + "Templates" + Path.DirectorySeparatorChar.ToString() + "EmailTemplates"
                    + Path.DirectorySeparatorChar.ToString() + "NewletterTemplate.htm";

                var BusEmail = new MailAddress("rendezvousrestaurantdut@gmail.com", "Rendezvous Restuarant");
                var email = new MailAddress(Email, Name);
                var pass = "DUTRendezvous123";
                var subject = Sub;
                //var body = BodMessage;
                //Assigning the template to the body of the email
                string HtmlBody = "";
                using (StreamReader streamReader = System.IO.File.OpenText(PathToFile))
                {
                    HtmlBody = streamReader.ReadToEnd();
                }

                // HtmlBody = HtmlBody.Replace("#temp#", "Rydell");
                string UrlMain = "https://2021grp27.azurewebsites.net/Customer/Home/Details/";
                string UrlImageBase = "https://2021grp27.azurewebsites.net/images/";
                string NewsletterItems = "<table border ="+1+"cellpadding="+0+" width="+600+">";
                foreach (var item in objMenuItems)
                {
                    var NameHyperLink = "<a href=" + UrlMain + item.Id + ">"+item.Name+"</a>";
                    string Img = item.Image;
                    Img = Img.Replace(@"\images\",string.Empty);

                    var LinkToImage = "<img src=" + UrlImageBase + Img + ">";

                    NewsletterItems += "<tr><td>" +
                        LinkToImage + "</td><td><h3>" +
                          NameHyperLink +
                         "</h3></td><td><h3>" +
                        item.Price.ToString("C") +
                        "</h3></td></tr>";
                }
                NewsletterItems += "</table>";

                HtmlBody = HtmlBody.Replace("#MenuItem#", NewsletterItems);

                var body = HtmlBody;
                var smtp = new SmtpClient
                {
                    Host = "smtp.gmail.com",
                    Port = 587,
                    EnableSsl = true,
                    DeliveryMethod = SmtpDeliveryMethod.Network,
                    UseDefaultCredentials = false,
                    Credentials = new NetworkCredential(BusEmail.Address, pass)
                };
                using (var message = new MailMessage(BusEmail, email)
                {
                    Subject = subject,
                    Body = body,
                    IsBodyHtml = true,
                    BodyEncoding = System.Text.Encoding.UTF8
                })
                {
                    smtp.Send(message);
                }
                return true;
            }
            catch
            {
                return false;
            }

        }
    }
}

AppDevProjectGroup27/Areas/Admin/Views/Special/Index.cshtml
@model AppDevProjectGroup27.Models.ViewModels.SpecialVM
@{
    ViewData["Title"] = "Newsletter |";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<br />
<br />
<partial name="_StatusMessage" model="Model.StatusMessage" />
<div class="border backgroundWhiteBorder">
    <div class="row">
        <div class="col-6">
            <h2 class="text-info">Newsletter</h2>
        </div>
    </div>
    <br />
    @if (Model.MenuItems.Count() > 0)
    {
        @using (Html.BeginForm("Index", "Special", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div>
                Subject of Newsletter: &nbsp; <input class="text-box" type="text" asp-for="@Model.Subject" />
                &emsp;
                <input type="submit" value="Send Newsletter" class="btn btn-info" />
            </div>
        }
        <br />
    }
    <div>
        @if (Model.MenuItems.Count() > 0)
        {
            <table class="table table-striped border">
                <tr class="table-secondary">
                    <th>
                        @Html.DisplayNameFor(m => m.MenuItems.FirstOrDefault().Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(m => m.MenuItems.FirstOrDefault().Price)
                    </th>
                    <th>
                        @Html.DisplayNameFor(m => m.MenuItems.FirstOrDefault().CategoryId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(m => m.MenuItems.FirstOrDefault().SubCategoryId)
                    </th>
                    <th>

                    </th>
                </tr>
                @foreach (var item in Model.MenuItems)
                {
                    <tr>
                        <td style="vertical-align:middle">
                            @Html.DisplayFor(m => item.Name)
                        </td>
                        <td style="vertical-align:middle">
                            @Html.DisplayFor(m => item.Price)
                        </td>
                        <td style="vertical-align:middle">
                            @Html.DisplayFor(m => item.Category.Name)
                        </td>
                        <td style="vertical-align:middle">
                            @Html.DisplayFor(m => item.SubCategory.Name)
                        </td>
                        <td class="col-md-3 col-sm-12">
                            <img src="@item.Image" width="99%" style="border-radius:5px;border:1px solid #bbb9b9" />
                        </td>
                    </tr>
                }

            </table>
        }
        else
        {
            <p>No Items are on Special...</p>
        }
    </div>
</div>